<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>CreateQuoteHome</name>
   <tag></tag>
   <elementGuidId>fc677d8f-fcb3-4f46-9ee3-4a94a1cf4c01</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;Step1\&quot;: {\n        \&quot;CURP\&quot;: \&quot;${rCURP}\&quot;,\n        \&quot;FirstName\&quot;: \&quot;${rFirstName}\&quot;,\n        \&quot;LastName\&quot;: \&quot;${rLastName}\&quot;,\n        \&quot;RFC\&quot;: \&quot;${rRFC}\&quot;,\n        \&quot;PhoneNumber\&quot;:\&quot;${rPhoneNumber}\&quot;,\n        \&quot;Email\&quot;: \&quot;${rEmail}\&quot;,\n        \&quot;BirthDate\&quot;: \&quot;${rBirthDate}\&quot;\n    },\n    \&quot;Step2\&quot;: {\n        \&quot;Address\&quot;: {\n            \&quot;Street\&quot;: \&quot;${rStreet}\&quot;,\n            \&quot;ExternalNumber\&quot;: \&quot;${rExternalNumber}\&quot;,\n            \&quot;InternalNumber\&quot;: \&quot;${rInternalNumber}\&quot;,\n            \&quot;City\&quot;: \&quot;${rCity}\&quot;,\n            \&quot;Country\&quot;: \&quot;${rCountry}\&quot;,\n            \&quot;State\&quot;: \&quot;${rState}\&quot;,\n            \&quot;Town\&quot;: \&quot;${rTown}\&quot;,\n            \&quot;PostalCode\&quot;: \&quot;${rPostalCode}\&quot;\n        }\n    },\n    \&quot;Step3\&quot;: {\n        \&quot;BuildingInformation\&quot;: {\n            \&quot;Address\&quot;: {\n                \&quot;Street\&quot;: \&quot;${rStreetEdifi}\&quot;,\n\t\t\t\t\&quot;ExternalNumber\&quot;: \&quot;${rExternalNumberEdifi}\&quot;,\n\t\t\t\t\&quot;InternalNumber\&quot;: \&quot;${rInternalNumberEdifi}\&quot;,\n\t\t\t\t\&quot;City\&quot;: \&quot;${rCityEdifi}\&quot;,\n\t\t\t\t\&quot;Country\&quot;: \&quot;${rCountryEdifi}\&quot;,\n\t\t\t\t\&quot;State\&quot;: \&quot;${rStateEdifi}\&quot;,\n\t\t\t\t\&quot;Town\&quot;: \&quot;${rTownEdifi}\&quot;,\n\t\t\t\t\&quot;PostalCode\&quot;: \&quot;${rPostalCodeEdifi}\&quot;\n            },\n            \&quot;Value\&quot;: ${rValue},\n            \&quot;ContentsInsuredAmount\&quot;: ${rPorcentaje},\n            \&quot;Levels\&quot;: \&quot;${rLevels}\&quot;,\n            \&quot;BuildingAge\&quot;: \&quot;${rAnoEdifi}\&quot;,\n            \&quot;MarDistance\&quot;: ${rMarDistance}\n        },\n        \&quot;ContentsInformation\&quot;: {\n            \&quot;Value\&quot;: ${rValueContenido}\n        }\n    },\n    \&quot;Step4\&quot;: {\n        \&quot;Package\&quot;: {\n            \&quot;branch\&quot;: \&quot;${rBranch}\&quot;,\n            \&quot;Code\&quot;: \&quot;${rCode}\&quot;,\n            \&quot;StartDate\&quot;: \&quot;${rStartDate}\&quot;,\n            \&quot;EndDate\&quot;: \&quot;${rEndDate}\&quot;,\n            \&quot;Amount\&quot;: ${primaTotal},\n            \&quot;total\&quot;: ${rTotal},\n            \&quot;taxAmount\&quot;: ${rTaxAmount},\n            \&quot;priceWithExpense\&quot;: ${rPriceWithExpense},\n            \&quot;expense\&quot;: ${rExpense},\n            \&quot;numInstallments\&quot;: \&quot;${rNumInstallments}\&quot;,\n            \&quot;expenseOnFirstInstallment\&quot;: ${rExpenseOnFirstInstallment},\n            \&quot;installmentAmount\&quot;: ${rInstallmentAmount}\n        },\n        \&quot;PackageCoverage\&quot;: [\n            {\n                \&quot;code\&quot;: \&quot;${code1}\&quot;,\n                \&quot;price\&quot;: ${price1},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada1},\n                \&quot;name\&quot;: \&quot;${name1}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code2}\&quot;,\n                \&quot;price\&quot;: ${price2},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada2},\n                \&quot;name\&quot;: \&quot;${name2}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code3}\&quot;,\n                \&quot;price\&quot;: ${price3},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada3},\n                \&quot;name\&quot;: \&quot;${name3}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code4}\&quot;,\n                \&quot;price\&quot;: ${price4},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada4},\n                \&quot;name\&quot;: \&quot;${name4}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code5}\&quot;,\n                \&quot;price\&quot;: ${price5},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada5},\n                \&quot;name\&quot;: \&quot;${name5}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code6}\&quot;,\n                \&quot;price\&quot;: ${price6},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada6},\n                \&quot;name\&quot;: \&quot;${name6}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code7}\&quot;,\n                \&quot;price\&quot;: ${price7},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada7},\n                \&quot;name\&quot;: \&quot;${name7}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code8}\&quot;,\n                \&quot;price\&quot;: ${price8},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada8},\n                \&quot;name\&quot;: \&quot;${name8}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code9}\&quot;,\n                \&quot;price\&quot;: ${price9},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada9},\n                \&quot;name\&quot;: \&quot;${name9}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code10}\&quot;,\n                \&quot;price\&quot;: ${price10},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada10},\n                \&quot;name\&quot;: \&quot;${name10}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code11}\&quot;,\n                \&quot;price\&quot;: ${price11},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada11},\n                \&quot;name\&quot;: \&quot;${name11}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code12}\&quot;,\n                \&quot;price\&quot;: ${price12},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada12},\n                \&quot;name\&quot;: \&quot;${name12}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code13}\&quot;,\n                \&quot;price\&quot;: ${price13},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada13},\n                \&quot;name\&quot;: \&quot;${name13}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code14}\&quot;,\n                \&quot;price\&quot;: ${price14},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada14},\n                \&quot;name\&quot;: \&quot;${name14}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code15}\&quot;,\n                \&quot;price\&quot;: ${price15},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada15},\n                \&quot;name\&quot;: \&quot;${name15}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code16}\&quot;,\n                \&quot;price\&quot;: ${price16},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada16},\n                \&quot;name\&quot;: \&quot;${name16}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code17}\&quot;,\n                \&quot;price\&quot;: ${price17},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada17},\n                \&quot;name\&quot;: \&quot;${name17}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code18}\&quot;,\n                \&quot;price\&quot;: ${price18},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada18},\n                \&quot;name\&quot;: \&quot;${name18}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code19}\&quot;,\n                \&quot;price\&quot;: ${price19},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada19},\n                \&quot;name\&quot;: \&quot;${name19}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code20}\&quot;,\n                \&quot;price\&quot;: ${price20},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada20},\n                \&quot;name\&quot;: \&quot;${name20}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code21}\&quot;,\n                \&quot;price\&quot;: ${price21},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada21},\n                \&quot;name\&quot;: \&quot;${name21}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code22}\&quot;,\n                \&quot;price\&quot;: ${price22},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada22},\n                \&quot;name\&quot;: \&quot;${name22}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code23}\&quot;,\n                \&quot;price\&quot;: ${price23},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada23},\n                \&quot;name\&quot;: \&quot;${name23}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code24}\&quot;,\n                \&quot;price\&quot;: ${price24},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada24},\n                \&quot;name\&quot;: \&quot;${name24}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code25}\&quot;,\n                \&quot;price\&quot;: ${price25},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada25},\n                \&quot;name\&quot;: \&quot;${name25}\&quot;\n            },\n\t\t\t{\n                \&quot;code\&quot;: \&quot;${code26}\&quot;,\n                \&quot;price\&quot;: ${price26},\n                \&quot;insuredAmount\&quot;: ${suumaAsegurada26},\n                \&quot;name\&quot;: \&quot;${name26}\&quot;\n            }\n        ]\n    },\n    \&quot;Step5\&quot;: {\n        \&quot;Bank\&quot;: \&quot;${rBank}\&quot;,\n        \&quot;CardCVV\&quot;: \&quot;${rCardCVV}\&quot;,\n        \&quot;FirstName\&quot;: \&quot;${rFirstNameBan}\&quot;,\n        \&quot;LastName\&quot;: \&quot;${rLastNameBan}\&quot;,\n        \&quot;PaymentPeriod\&quot;: \&quot;${rPaymentPeriod}\&quot;,\n        \&quot;TypeOfCard\&quot;: \&quot;${rTypeOfCard}\&quot;,\n        \&quot;Amount\&quot;: ${rAmount},\n        \&quot;IsRecurringPayment\&quot;: ${rIsRecurringPayment},\n        \&quot;CardMonth\&quot;: ${rCardMonth},\n        \&quot;CardNumber\&quot;: ${rCardNumber},\n        \&quot;CardYear\&quot;: ${rCardYear}\n    }\n}\n&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>1a539911-b0d5-4b36-82bf-4d9f7c490efb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${GlobalVariable.TOKEN}</value>
      <webElementGuid>8e74a7ee-f38d-47e2-8607-1e63ae4a185c</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.6.5</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://segbanortesfi--qa.sandbox.my.salesforce.com/services/apexrest/vlocity_ins/v1/integrationprocedure/ClbIns_CreateQuote/</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'DOHF660129HVZMRR08'</defaultValue>
      <description></description>
      <id>0e3c880c-4750-40f7-a2c7-adb6dd3dbf4f</id>
      <masked>false</masked>
      <name>rCURP</name>
   </variables>
   <variables>
      <defaultValue>'Mary'</defaultValue>
      <description></description>
      <id>a95906bb-465d-42a5-a024-fb1323f9ee7b</id>
      <masked>false</masked>
      <name>rFirstName</name>
   </variables>
   <variables>
      <defaultValue>'Santos'</defaultValue>
      <description></description>
      <id>798be488-2b24-4051-a52b-c3b953f454b8</id>
      <masked>false</masked>
      <name>rLastName</name>
   </variables>
   <variables>
      <defaultValue>'MOML770826VA'</defaultValue>
      <description></description>
      <id>328bf17b-7ddc-4115-844b-b16e03562e39</id>
      <masked>false</masked>
      <name>rRFC</name>
   </variables>
   <variables>
      <defaultValue>'5512345987'</defaultValue>
      <description></description>
      <id>4fb5254e-2c03-4c05-ab5b-73419378f1b2</id>
      <masked>false</masked>
      <name>rPhoneNumber</name>
   </variables>
   <variables>
      <defaultValue>'victor.rojas.guerrero@banorte.com'</defaultValue>
      <description></description>
      <id>9005358d-eb5a-4572-8f89-a983e3e8eed9</id>
      <masked>false</masked>
      <name>rEmail</name>
   </variables>
   <variables>
      <defaultValue>'1982-06-21'</defaultValue>
      <description></description>
      <id>25832f03-cdf2-449e-842c-ef8988b1236a</id>
      <masked>false</masked>
      <name>rBirthDate</name>
   </variables>
   <variables>
      <defaultValue>'Calle 3'</defaultValue>
      <description></description>
      <id>4a51d13d-e9d1-4761-a2c7-5015b378e499</id>
      <masked>false</masked>
      <name>rStreet</name>
   </variables>
   <variables>
      <defaultValue>'546'</defaultValue>
      <description></description>
      <id>9aeb8e9c-2479-4797-8be3-d4b4f576748f</id>
      <masked>false</masked>
      <name>rExternalNumber</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>77821a43-bf91-4afe-afdf-50c87e3da7b8</id>
      <masked>false</masked>
      <name>rInternalNumber</name>
   </variables>
   <variables>
      <defaultValue>'Benito Juárez'</defaultValue>
      <description></description>
      <id>c13d5b4d-ca4c-4263-ad0e-78866c3312f1</id>
      <masked>false</masked>
      <name>rCity</name>
   </variables>
   <variables>
      <defaultValue>'MEXICO'</defaultValue>
      <description></description>
      <id>d321a513-d2db-4428-8a8d-45e173b69762</id>
      <masked>false</masked>
      <name>rCountry</name>
   </variables>
   <variables>
      <defaultValue>'CIUDAD DE MÉXICO'</defaultValue>
      <description></description>
      <id>fe96f983-53b8-4b94-810e-e856f766bc68</id>
      <masked>false</masked>
      <name>rState</name>
   </variables>
   <variables>
      <defaultValue>'Del Valle Centro'</defaultValue>
      <description></description>
      <id>5da54806-f2d2-4965-bcb4-6fff04c9c310</id>
      <masked>false</masked>
      <name>rTown</name>
   </variables>
   <variables>
      <defaultValue>'03100'</defaultValue>
      <description></description>
      <id>c70ee713-b337-4b7c-bc48-0d3ca7ef74c9</id>
      <masked>false</masked>
      <name>rPostalCode</name>
   </variables>
   <variables>
      <defaultValue>'Calle 3'</defaultValue>
      <description></description>
      <id>990f94f3-359d-472d-ba0e-72519e6d4f8b</id>
      <masked>false</masked>
      <name>rStreetEdifi</name>
   </variables>
   <variables>
      <defaultValue>'546 D'</defaultValue>
      <description></description>
      <id>f12ccc78-c6e1-413a-abde-90714c7469f7</id>
      <masked>false</masked>
      <name>rExternalNumberEdifi</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5c16a4d6-71ce-44c9-810d-5a9dcffe5fcc</id>
      <masked>false</masked>
      <name>rInternalNumberEdifi</name>
   </variables>
   <variables>
      <defaultValue>'Benito Juárez'</defaultValue>
      <description></description>
      <id>04ee71b2-71da-4173-a3bc-706dffef71f4</id>
      <masked>false</masked>
      <name>rCityEdifi</name>
   </variables>
   <variables>
      <defaultValue>'MEXICO'</defaultValue>
      <description></description>
      <id>9d88a0da-24f0-47bd-8c26-221d11e77938</id>
      <masked>false</masked>
      <name>rCountryEdifi</name>
   </variables>
   <variables>
      <defaultValue>'CIUDAD DE MÉXICO'</defaultValue>
      <description></description>
      <id>cf2fba87-87d1-4e5d-bca9-6e5c4b851c92</id>
      <masked>false</masked>
      <name>rStateEdifi</name>
   </variables>
   <variables>
      <defaultValue>'Del Valle Centro'</defaultValue>
      <description></description>
      <id>8288dd0e-af4b-4afd-a8a3-f74591e7b629</id>
      <masked>false</masked>
      <name>rTownEdifi</name>
   </variables>
   <variables>
      <defaultValue>'03100'</defaultValue>
      <description></description>
      <id>8259a1da-9c54-4446-b934-e87428989d1c</id>
      <masked>false</masked>
      <name>rPostalCodeEdifi</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>fe105474-3e1f-4a6e-b0b9-df638c9c073a</id>
      <masked>false</masked>
      <name>rValue</name>
   </variables>
   <variables>
      <defaultValue>40</defaultValue>
      <description></description>
      <id>36943a1f-5363-45aa-b942-a775814bfaa7</id>
      <masked>false</masked>
      <name>rPorcentaje</name>
   </variables>
   <variables>
      <defaultValue>'3'</defaultValue>
      <description></description>
      <id>7251a0ca-e965-4a52-8c92-3330bf4c7930</id>
      <masked>false</masked>
      <name>rLevels</name>
   </variables>
   <variables>
      <defaultValue>'&lt;=50'</defaultValue>
      <description></description>
      <id>3dd83d2c-2fa7-40e0-8565-9c862f03b2eb</id>
      <masked>false</masked>
      <name>rAnoEdifi</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>911fabd9-09f5-45f4-9559-73f37c9a1510</id>
      <masked>false</masked>
      <name>rMarDistance</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>c2fe7418-d873-4b8c-8f8b-9fccc7f73e9b</id>
      <masked>false</masked>
      <name>rValueContenido</name>
   </variables>
   <variables>
      <defaultValue>'2023-12-06'</defaultValue>
      <description></description>
      <id>79ab63d4-201e-4f0a-b7e1-b5af150b0d15</id>
      <masked>false</masked>
      <name>rStartDate</name>
   </variables>
   <variables>
      <defaultValue>'2024-12-06'</defaultValue>
      <description></description>
      <id>7ddcbb06-f2ac-43e3-9639-aa5e63092567</id>
      <masked>false</masked>
      <name>rEndDate</name>
   </variables>
   <variables>
      <defaultValue>5370.41</defaultValue>
      <description></description>
      <id>25d4f731-3664-448c-af97-8812d4005b29</id>
      <masked>false</masked>
      <name>primaTotal</name>
   </variables>
   <variables>
      <defaultValue>6577.68</defaultValue>
      <description></description>
      <id>372e703b-9098-4e69-acee-3417d57bd8ad</id>
      <masked>false</masked>
      <name>rTotal</name>
   </variables>
   <variables>
      <defaultValue>907.27</defaultValue>
      <description></description>
      <id>b0014e8d-0abc-4fcd-a3b1-9a8139bab8c7</id>
      <masked>false</masked>
      <name>rTaxAmount</name>
   </variables>
   <variables>
      <defaultValue>'RCF1'</defaultValue>
      <description></description>
      <id>5a280a63-ec77-4a7f-abed-f1d62bb96327</id>
      <masked>false</masked>
      <name>code1</name>
   </variables>
   <variables>
      <defaultValue>80.7</defaultValue>
      <description></description>
      <id>57fabe7d-521c-4719-960d-99602fd58b11</id>
      <masked>false</masked>
      <name>price1</name>
   </variables>
   <variables>
      <defaultValue>1000000</defaultValue>
      <description></description>
      <id>caace8ee-16e0-4ddc-8be4-cb3a24db9bef</id>
      <masked>false</masked>
      <name>suumaAsegurada1</name>
   </variables>
   <variables>
      <defaultValue>'RCGE-PROPIO-FAMILIAR'</defaultValue>
      <description></description>
      <id>a27823a2-98c3-4c67-93d3-86efded09b07</id>
      <masked>false</masked>
      <name>name1</name>
   </variables>
   <variables>
      <defaultValue>'RB03'</defaultValue>
      <description></description>
      <id>bfc6a042-729b-4bae-b327-8a0285891018</id>
      <masked>false</masked>
      <name>code2</name>
   </variables>
   <variables>
      <defaultValue>338.2</defaultValue>
      <description></description>
      <id>3641bfd4-de45-4e8e-99fa-dd3849c5b58e</id>
      <masked>false</masked>
      <name>price2</name>
   </variables>
   <variables>
      <defaultValue>100000</defaultValue>
      <description></description>
      <id>398730c5-2b93-4886-a9f4-c661d8cbc8e2</id>
      <masked>false</masked>
      <name>suumaAsegurada2</name>
   </variables>
   <variables>
      <defaultValue>'DMRB-PROPIO-ROBO CON VIOLENCIA Y ASALTO'</defaultValue>
      <description></description>
      <id>cbf41b67-04a4-4f77-bb0c-a2bdd9072a8b</id>
      <masked>false</masked>
      <name>name2</name>
   </variables>
   <variables>
      <defaultValue>'RB15'</defaultValue>
      <description></description>
      <id>0bbcb3d3-254f-4cb0-ab33-1d5e1597c14d</id>
      <masked>false</masked>
      <name>code3</name>
   </variables>
   <variables>
      <defaultValue>0.45</defaultValue>
      <description></description>
      <id>79aa2dbb-a6e6-43b9-9cb3-491159865ece</id>
      <masked>false</masked>
      <name>price3</name>
   </variables>
   <variables>
      <defaultValue>4500</defaultValue>
      <description></description>
      <id>cccd3d9d-49b6-46c2-8055-4e0355da9592</id>
      <masked>false</masked>
      <name>suumaAsegurada3</name>
   </variables>
   <variables>
      <defaultValue>'DMRB-PROPIO-AJUSTE AUTOMÁTICO POR INFLACIÓN'</defaultValue>
      <description></description>
      <id>719519e1-06eb-4248-9830-dc304cf8a56d</id>
      <masked>false</masked>
      <name>name3</name>
   </variables>
   <variables>
      <defaultValue>'MA01'</defaultValue>
      <description></description>
      <id>14433c94-6415-48b2-b495-7dd7626bf9ce</id>
      <masked>false</masked>
      <name>code4</name>
   </variables>
   <variables>
      <defaultValue>35.13</defaultValue>
      <description></description>
      <id>130c1646-51eb-4549-966d-e03438679a36</id>
      <masked>false</masked>
      <name>price4</name>
   </variables>
   <variables>
      <defaultValue>50000</defaultValue>
      <description></description>
      <id>699c2a4c-18bd-41fb-95a9-072037e977d1</id>
      <masked>false</masked>
      <name>suumaAsegurada4</name>
   </variables>
   <variables>
      <defaultValue>'DMED-PROPIO-DAÑOS MATERIALES'</defaultValue>
      <description></description>
      <id>3f5a453a-74b0-4ff1-b963-aad2d7c7628b</id>
      <masked>false</masked>
      <name>name4</name>
   </variables>
   <variables>
      <defaultValue>'I005E'</defaultValue>
      <description></description>
      <id>3df77ee7-dae6-4ea4-9e3d-19d13025f4f2</id>
      <masked>false</masked>
      <name>code5</name>
   </variables>
   <variables>
      <defaultValue>150.9</defaultValue>
      <description></description>
      <id>6586616a-82fe-4117-9e93-06b2e89c74cc</id>
      <masked>false</masked>
      <name>price5</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>3ea12261-0857-425a-8bf7-c26d3f12fd5c</id>
      <masked>false</masked>
      <name>suumaAsegurada5</name>
   </variables>
   <variables>
      <defaultValue>'INCE-EDIFICIO-TODO RIESGO (S)'</defaultValue>
      <description></description>
      <id>09e05d7a-75ff-471f-ab8a-d925a465291b</id>
      <masked>false</masked>
      <name>name5</name>
   </variables>
   <variables>
      <defaultValue>'I013E'</defaultValue>
      <description></description>
      <id>8eb0fd7a-9c9a-465e-8372-347896554148</id>
      <masked>false</masked>
      <name>code6</name>
   </variables>
   <variables>
      <defaultValue>30.16</defaultValue>
      <description></description>
      <id>d95f7a78-02f1-4346-bf5b-a5b0e6f4e5c7</id>
      <masked>false</masked>
      <name>price6</name>
   </variables>
   <variables>
      <defaultValue>400000</defaultValue>
      <description></description>
      <id>40e65e9c-36fc-474e-acb0-edc6546cc325</id>
      <masked>false</masked>
      <name>suumaAsegurada6</name>
   </variables>
   <variables>
      <defaultValue>'INCE-EDIFICIO-REMOCIÓN DE ESCOMBROS'</defaultValue>
      <description></description>
      <id>b798cbd1-a2fe-4bda-b1d7-d917d84485d6</id>
      <masked>false</masked>
      <name>name6</name>
   </variables>
   <variables>
      <defaultValue>'I001E'</defaultValue>
      <description></description>
      <id>f9610d56-12a1-47a3-8f0d-931b171b6c02</id>
      <masked>false</masked>
      <name>code7</name>
   </variables>
   <variables>
      <defaultValue>181.08</defaultValue>
      <description></description>
      <id>ccc6bcf6-1531-415d-8330-05e64972f35c</id>
      <masked>false</masked>
      <name>price7</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>acc09f05-6047-4019-a641-8606f135354a</id>
      <masked>false</masked>
      <name>suumaAsegurada7</name>
   </variables>
   <variables>
      <defaultValue>'INCE-EDIFICIO-INCENDIO Y/O RAYO'</defaultValue>
      <description></description>
      <id>1e6127f8-8468-4549-97cd-c17e54feaf5a</id>
      <masked>false</masked>
      <name>name7</name>
   </variables>
   <variables>
      <defaultValue>'I003E'</defaultValue>
      <description></description>
      <id>78314703-0e62-492b-a2e2-bba146126b8d</id>
      <masked>false</masked>
      <name>code8</name>
   </variables>
   <variables>
      <defaultValue>90.54</defaultValue>
      <description></description>
      <id>99a52457-9949-48fc-8c6f-425599437341</id>
      <masked>false</masked>
      <name>price8</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>507e064b-242c-48a1-91d9-b7422dc6958b</id>
      <masked>false</masked>
      <name>suumaAsegurada8</name>
   </variables>
   <variables>
      <defaultValue>'INCE-EDIFICIO-HUELGAS Y ALBOROTOS POPULARES (S)'</defaultValue>
      <description></description>
      <id>0a29377b-3eee-4e87-bf37-ec9fcf8bbb40</id>
      <masked>false</masked>
      <name>name8</name>
   </variables>
   <variables>
      <defaultValue>'I004E'</defaultValue>
      <description></description>
      <id>1ce48452-464b-410f-9aec-c693688d4a20</id>
      <masked>false</masked>
      <name>code9</name>
   </variables>
   <variables>
      <defaultValue>90.54</defaultValue>
      <description></description>
      <id>a88177e9-b910-4dcd-8d06-a9431ca2824d</id>
      <masked>false</masked>
      <name>price9</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>a1310209-59fd-4fa6-8044-06c762a1825e</id>
      <masked>false</masked>
      <name>suumaAsegurada9</name>
   </variables>
   <variables>
      <defaultValue>'INCE-EDIFICIO-EXTENSIÓN DE CUBIERTA (S)'</defaultValue>
      <description></description>
      <id>20769b08-2ae0-41cf-a2d4-96b7ec5e50e0</id>
      <masked>false</masked>
      <name>name9</name>
   </variables>
   <variables>
      <defaultValue>'I002E'</defaultValue>
      <description></description>
      <id>f7783e53-ecb0-4aec-a89c-505d1c5f1942</id>
      <masked>false</masked>
      <name>code10</name>
   </variables>
   <variables>
      <defaultValue>90.54</defaultValue>
      <description></description>
      <id>ffd3b620-76a0-49db-97f3-cb2ab46e88cb</id>
      <masked>false</masked>
      <name>price10</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>9992fd5f-26ec-46d0-8cb4-1f6b88f8ada2</id>
      <masked>false</masked>
      <name>suumaAsegurada10</name>
   </variables>
   <variables>
      <defaultValue>'INCE-EDIFICIO-EXPLOSIÓN (S)'</defaultValue>
      <description></description>
      <id>0580cb5a-f38e-44fd-9338-0f5226d22484</id>
      <masked>false</masked>
      <name>name10</name>
   </variables>
   <variables>
      <defaultValue>'I011E'</defaultValue>
      <description></description>
      <id>602f2550-0ddf-4f15-b64c-4d11abfdbf2c</id>
      <masked>false</masked>
      <name>code11</name>
   </variables>
   <variables>
      <defaultValue>18</defaultValue>
      <description></description>
      <id>6c393d6e-85cd-40d5-8f12-6bf93aae3092</id>
      <masked>false</masked>
      <name>price11</name>
   </variables>
   <variables>
      <defaultValue>180000</defaultValue>
      <description></description>
      <id>7ce5b903-ba02-463b-aa00-fb51718fd765</id>
      <masked>false</masked>
      <name>suumaAsegurada11</name>
   </variables>
   <variables>
      <defaultValue>'INCE-EDIFICIO-AJUSTE AUTOMÁTICO POR INFLACIÓN (S)'</defaultValue>
      <description></description>
      <id>0622dec8-e1b3-4aa8-bb42-859082674b20</id>
      <masked>false</masked>
      <name>name11</name>
   </variables>
   <variables>
      <defaultValue>'TE01E'</defaultValue>
      <description></description>
      <id>81f88b8e-6b10-4d58-922b-0c17fede754c</id>
      <masked>false</masked>
      <name>code12</name>
   </variables>
   <variables>
      <defaultValue>2676.44</defaultValue>
      <description></description>
      <id>28448f04-46f9-4623-b308-5cd51267c205</id>
      <masked>false</masked>
      <name>price12</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>f7cf0c3b-91d3-42b6-b2ec-100e18e2de82</id>
      <masked>false</masked>
      <name>suumaAsegurada12</name>
   </variables>
   <variables>
      <defaultValue>'TEEV-EDIFICIO-TERREMOTO Y ERUPCIÓN VOLCÁNICA'</defaultValue>
      <description></description>
      <id>22a7ae02-a62c-42d8-adb4-432286424e23</id>
      <masked>false</masked>
      <name>name12</name>
   </variables>
   <variables>
      <defaultValue>'TE02E'</defaultValue>
      <description></description>
      <id>964494b1-b132-4e23-b06a-6b239cd3a58e</id>
      <masked>false</masked>
      <name>code13</name>
   </variables>
   <variables>
      <defaultValue>30.16</defaultValue>
      <description></description>
      <id>d2ccd55b-8e4b-4b90-985f-918ca6e4ebd2</id>
      <masked>false</masked>
      <name>price13</name>
   </variables>
   <variables>
      <defaultValue>400000</defaultValue>
      <description></description>
      <id>2a6fd46b-dbda-4ba6-875a-c35242204d26</id>
      <masked>false</masked>
      <name>suumaAsegurada13</name>
   </variables>
   <variables>
      <defaultValue>'TEEV-EDIFICIO-REMOCIÓN DE ESCOMBROS'</defaultValue>
      <description></description>
      <id>0a9cfd36-5f42-4969-9ad8-307a7cc1a539</id>
      <masked>false</masked>
      <name>name13</name>
   </variables>
   <variables>
      <defaultValue>'RH01E'</defaultValue>
      <description></description>
      <id>b824fe6e-c02f-41f5-8cfa-9d248b83975b</id>
      <masked>false</masked>
      <name>code14</name>
   </variables>
   <variables>
      <defaultValue>505.2</defaultValue>
      <description></description>
      <id>0765736f-8d7c-4658-9e04-b16360fddff4</id>
      <masked>false</masked>
      <name>price14</name>
   </variables>
   <variables>
      <defaultValue>4000000</defaultValue>
      <description></description>
      <id>8aa9efc1-d8a1-4f67-a4a0-74ba1a2fcc27</id>
      <masked>false</masked>
      <name>suumaAsegurada14</name>
   </variables>
   <variables>
      <defaultValue>'RHMT-EDIFICIO-RIESGOS HIDROMETEOROLÓGICOS'</defaultValue>
      <description></description>
      <id>6f718c88-8fc2-427d-8025-2df18e8a9a5f</id>
      <masked>false</masked>
      <name>name14</name>
   </variables>
   <variables>
      <defaultValue>'RH02E'</defaultValue>
      <description></description>
      <id>70239088-2ff1-4b1f-af01-6aa7938d7c1d</id>
      <masked>false</masked>
      <name>code15</name>
   </variables>
   <variables>
      <defaultValue>30.16</defaultValue>
      <description></description>
      <id>9439cf47-7d51-4e9d-9b4a-40a3d5dcba33</id>
      <masked>false</masked>
      <name>price15</name>
   </variables>
   <variables>
      <defaultValue>400000</defaultValue>
      <description></description>
      <id>93071dff-2b59-4bc4-b074-0c5a2bcaca1c</id>
      <masked>false</masked>
      <name>suumaAsegurada15</name>
   </variables>
   <variables>
      <defaultValue>'RHMT-EDIFICIO-REMOCIÓN DE ESCOMBROS'</defaultValue>
      <description></description>
      <id>a5193330-c63e-4c1c-8d28-52a13e2663a1</id>
      <masked>false</masked>
      <name>name15</name>
   </variables>
   <variables>
      <defaultValue>'I005C'</defaultValue>
      <description></description>
      <id>5e7299af-500c-4a29-b803-d2bc192de874</id>
      <masked>false</masked>
      <name>code16</name>
   </variables>
   <variables>
      <defaultValue>60.36</defaultValue>
      <description></description>
      <id>c7e9c067-9e7f-40b2-b4eb-3799a86f8bcf</id>
      <masked>false</masked>
      <name>price16</name>
   </variables>
   <variables>
      <defaultValue>1600000</defaultValue>
      <description></description>
      <id>69427b8e-963f-4a5f-91b4-d1a64dc527d6</id>
      <masked>false</masked>
      <name>suumaAsegurada16</name>
   </variables>
   <variables>
      <defaultValue>'INCE-CONTENIDO-TODO RIESGO (S)'</defaultValue>
      <description></description>
      <id>83462ec7-aaf7-4259-bb16-a83af492ce4d</id>
      <masked>false</masked>
      <name>name16</name>
   </variables>
   <variables>
      <defaultValue>'I013C'</defaultValue>
      <description></description>
      <id>1f74e996-0217-4d5a-9acc-269cf9a964dc</id>
      <masked>false</masked>
      <name>code17</name>
   </variables>
   <variables>
      <defaultValue>12.06</defaultValue>
      <description></description>
      <id>4520e24e-6e10-432b-b7b6-c1513905779d</id>
      <masked>false</masked>
      <name>price17</name>
   </variables>
   <variables>
      <defaultValue>160000</defaultValue>
      <description></description>
      <id>d20db165-80a0-4fba-abc4-82fe48d88592</id>
      <masked>false</masked>
      <name>suumaAsegurada17</name>
   </variables>
   <variables>
      <defaultValue>'INCE-CONTENIDO-REMOCIÓN DE ESCOMBROS'</defaultValue>
      <description></description>
      <id>f2b1cb43-7993-46ef-b921-d2db0e7fa088</id>
      <masked>false</masked>
      <name>name17</name>
   </variables>
   <variables>
      <defaultValue>'I001C'</defaultValue>
      <description></description>
      <id>82e87851-e72f-4b29-ac0a-1b419d04d1fa</id>
      <masked>false</masked>
      <name>code18</name>
   </variables>
   <variables>
      <defaultValue>72.43</defaultValue>
      <description></description>
      <id>6ccfa36c-0d28-4867-84c9-dfd3b99d7c82</id>
      <masked>false</masked>
      <name>price18</name>
   </variables>
   <variables>
      <defaultValue>1600000</defaultValue>
      <description></description>
      <id>121c75a4-6e99-4e70-9822-0785905304fe</id>
      <masked>false</masked>
      <name>suumaAsegurada18</name>
   </variables>
   <variables>
      <defaultValue>'INCE-CONTENIDO-INCENDIO Y/O RAYO'</defaultValue>
      <description></description>
      <id>9c49317e-1fa9-461a-ac8d-f3919e523e58</id>
      <masked>false</masked>
      <name>name18</name>
   </variables>
   <variables>
      <defaultValue>'I003C'</defaultValue>
      <description></description>
      <id>f764aa2e-833b-47df-a75c-4f5b3900bfd0</id>
      <masked>false</masked>
      <name>code19</name>
   </variables>
   <variables>
      <defaultValue>36.22</defaultValue>
      <description></description>
      <id>23877baa-7640-4092-91d7-9eabdcfe62da</id>
      <masked>false</masked>
      <name>price19</name>
   </variables>
   <variables>
      <defaultValue>1600000</defaultValue>
      <description></description>
      <id>4546b559-ec46-4c75-84ce-85523ffb9993</id>
      <masked>false</masked>
      <name>suumaAsegurada19</name>
   </variables>
   <variables>
      <defaultValue>'INCE-CONTENIDO-HUELGAS Y ALBOROTOS POPULARES (S)'</defaultValue>
      <description></description>
      <id>47252a6a-6d9e-4953-af38-7f595315e6c9</id>
      <masked>false</masked>
      <name>name19</name>
   </variables>
   <variables>
      <defaultValue>'I004C'</defaultValue>
      <description></description>
      <id>3b19aa3c-add3-4079-8640-85532827f427</id>
      <masked>false</masked>
      <name>code20</name>
   </variables>
   <variables>
      <defaultValue>36.22</defaultValue>
      <description></description>
      <id>aae403a1-41c4-4b1d-9b21-c3ebac520fb9</id>
      <masked>false</masked>
      <name>price20</name>
   </variables>
   <variables>
      <defaultValue>1600000</defaultValue>
      <description></description>
      <id>4aacdcf1-890c-420f-bf3e-d7f0b6343633</id>
      <masked>false</masked>
      <name>suumaAsegurada20</name>
   </variables>
   <variables>
      <defaultValue>'INCE-CONTENIDO-EXTENSIÓN DE CUBIERTA (S)'</defaultValue>
      <description></description>
      <id>6a1286bd-810b-48a8-814a-129e22afde8b</id>
      <masked>false</masked>
      <name>name20</name>
   </variables>
   <variables>
      <defaultValue>'I002C'</defaultValue>
      <description></description>
      <id>d3e4813a-2e23-43ed-9db6-829c10ccfaa1</id>
      <masked>false</masked>
      <name>code21</name>
   </variables>
   <variables>
      <defaultValue>36.22</defaultValue>
      <description></description>
      <id>9572d7eb-1c6e-46bd-98f3-a9157b0f054b</id>
      <masked>false</masked>
      <name>price21</name>
   </variables>
   <variables>
      <defaultValue>1600000</defaultValue>
      <description></description>
      <id>659260cd-2a71-4148-ba53-7481ae5a8f9c</id>
      <masked>false</masked>
      <name>suumaAsegurada21</name>
   </variables>
   <variables>
      <defaultValue>'INCE-CONTENIDO-EXPLOSIÓN (S)'</defaultValue>
      <description></description>
      <id>dc8f05d3-45c1-45ff-9483-44324b1a8e1d</id>
      <masked>false</masked>
      <name>name21</name>
   </variables>
   <variables>
      <defaultValue>'I011C'</defaultValue>
      <description></description>
      <id>4295b1b3-a306-4f9b-bd79-be02b2020131</id>
      <masked>false</masked>
      <name>code22</name>
   </variables>
   <variables>
      <defaultValue>7.2</defaultValue>
      <description></description>
      <id>e53ffda5-980e-4e1c-96f0-270737f2d3e4</id>
      <masked>false</masked>
      <name>price22</name>
   </variables>
   <variables>
      <defaultValue>72000</defaultValue>
      <description></description>
      <id>e3344f25-164c-47bb-bd5a-492aae2cdf08</id>
      <masked>false</masked>
      <name>suumaAsegurada22</name>
   </variables>
   <variables>
      <defaultValue>'INCE-CONTENIDO-AJUSTE AUTOMÁTICO POR INFLACIÓN (S)'</defaultValue>
      <description></description>
      <id>f7b2c26c-1e38-49ae-8ad2-707fd0cc650d</id>
      <masked>false</masked>
      <name>name22</name>
   </variables>
   <variables>
      <defaultValue>'TE01C'</defaultValue>
      <description></description>
      <id>94c6eafb-2f51-4f5b-adc8-4d4ab148ef67</id>
      <masked>false</masked>
      <name>code23</name>
   </variables>
   <variables>
      <defaultValue>535.3</defaultValue>
      <description></description>
      <id>47edbb4e-d30a-44ee-9389-a2d231157aa3</id>
      <masked>false</masked>
      <name>price23</name>
   </variables>
   <variables>
      <defaultValue>1600000</defaultValue>
      <description></description>
      <id>1375bcb7-8cf3-4f9c-8e27-cd1e1fe7dd82</id>
      <masked>false</masked>
      <name>suumaAsegurada23</name>
   </variables>
   <variables>
      <defaultValue>'TEEV-CONTENIDO-TERREMOTO Y ERUPCIÓN VOLCÁNICA'</defaultValue>
      <description></description>
      <id>08e6f72c-dc3e-4ec6-b512-beee76dc89d6</id>
      <masked>false</masked>
      <name>name23</name>
   </variables>
   <variables>
      <defaultValue>'TE02C'</defaultValue>
      <description></description>
      <id>a6783c42-86f0-453e-980f-6a6b19dc7742</id>
      <masked>false</masked>
      <name>code24</name>
   </variables>
   <variables>
      <defaultValue>12.06</defaultValue>
      <description></description>
      <id>f3617a92-aed3-42e7-905c-8a87719bdbe4</id>
      <masked>false</masked>
      <name>price24</name>
   </variables>
   <variables>
      <defaultValue>160000</defaultValue>
      <description></description>
      <id>3be5f43c-bdf1-4c9f-9047-489b76615d48</id>
      <masked>false</masked>
      <name>suumaAsegurada24</name>
   </variables>
   <variables>
      <defaultValue>'TEEV-CONTENIDO-REMOCIÓN DE ESCOMBROS'</defaultValue>
      <description></description>
      <id>419cf2c9-de84-4c4a-a941-afc7fc07587b</id>
      <masked>false</masked>
      <name>name24</name>
   </variables>
   <variables>
      <defaultValue>'RH01C'</defaultValue>
      <description></description>
      <id>7b653800-7dba-44df-88c0-1ae27cd23704</id>
      <masked>false</masked>
      <name>code25</name>
   </variables>
   <variables>
      <defaultValue>202.08</defaultValue>
      <description></description>
      <id>3796bbb1-2db3-4d09-99eb-68e4a2cee0a1</id>
      <masked>false</masked>
      <name>price25</name>
   </variables>
   <variables>
      <defaultValue>1600000</defaultValue>
      <description></description>
      <id>539994b0-8416-4738-8f2f-6cb6b51aa6a9</id>
      <masked>false</masked>
      <name>suumaAsegurada25</name>
   </variables>
   <variables>
      <defaultValue>'RHMT-CONTENIDO-RIESGOS HIDROMETEOROLÓGICOS'</defaultValue>
      <description></description>
      <id>87ca2b68-fccb-410e-af49-6793d9cd8140</id>
      <masked>false</masked>
      <name>name25</name>
   </variables>
   <variables>
      <defaultValue>'RH02C'</defaultValue>
      <description></description>
      <id>3cc8ae64-d1e7-4bfb-90f3-ad593617abf4</id>
      <masked>false</masked>
      <name>code26</name>
   </variables>
   <variables>
      <defaultValue>12.06</defaultValue>
      <description></description>
      <id>9b6efe32-ea1f-45fe-a4da-7199eae982d3</id>
      <masked>false</masked>
      <name>price26</name>
   </variables>
   <variables>
      <defaultValue>160000</defaultValue>
      <description></description>
      <id>e2a13e63-cb0c-442e-be55-3f1e58b23f01</id>
      <masked>false</masked>
      <name>suumaAsegurada26</name>
   </variables>
   <variables>
      <defaultValue>'RHMT-CONTENIDO-REMOCIÓN DE ESCOMBROS'</defaultValue>
      <description></description>
      <id>eab0f5d0-04c0-47a9-aeca-d2eb00f069d3</id>
      <masked>false</masked>
      <name>name26</name>
   </variables>
   <variables>
      <defaultValue>'072'</defaultValue>
      <description></description>
      <id>e236e723-8bda-46e7-a80c-e5371f8416b4</id>
      <masked>false</masked>
      <name>rBank</name>
   </variables>
   <variables>
      <defaultValue>'123'</defaultValue>
      <description></description>
      <id>a81490ff-bd48-481d-b2d6-9e8ae1aa3a08</id>
      <masked>false</masked>
      <name>rCardCVV</name>
   </variables>
   <variables>
      <defaultValue>'ROMINA RUBI'</defaultValue>
      <description></description>
      <id>57f35853-8c5d-4d18-9b24-c0fc9c243d62</id>
      <masked>false</masked>
      <name>rFirstNameBan</name>
   </variables>
   <variables>
      <defaultValue>'PÉREZ MÁRQUEZ'</defaultValue>
      <description></description>
      <id>41c1c8b5-09c5-419a-8baa-1c51d40fd1bf</id>
      <masked>false</masked>
      <name>rLastNameBan</name>
   </variables>
   <variables>
      <defaultValue>'012'</defaultValue>
      <description></description>
      <id>355167c6-7ce2-418a-98f7-d6566c9617ca</id>
      <masked>false</masked>
      <name>rPaymentPeriod</name>
   </variables>
   <variables>
      <defaultValue>'04'</defaultValue>
      <description></description>
      <id>c11a095b-83c9-45f6-8c70-ace8546871a2</id>
      <masked>false</masked>
      <name>rTypeOfCard</name>
   </variables>
   <variables>
      <defaultValue>5370.41</defaultValue>
      <description></description>
      <id>ff8ba1fd-8055-4c9c-af79-2ad9b98422b5</id>
      <masked>false</masked>
      <name>rAmount</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>ce402f82-b358-404a-948f-263b195da005</id>
      <masked>false</masked>
      <name>rIsRecurringPayment</name>
   </variables>
   <variables>
      <defaultValue>1</defaultValue>
      <description></description>
      <id>001775cf-d83b-41ef-b744-58ccaf291bc4</id>
      <masked>false</masked>
      <name>rCardMonth</name>
   </variables>
   <variables>
      <defaultValue>5101910203349540</defaultValue>
      <description></description>
      <id>b1b3dc99-3f12-4177-932d-fd2e8f2af1fc</id>
      <masked>false</masked>
      <name>rCardNumber</name>
   </variables>
   <variables>
      <defaultValue>2030</defaultValue>
      <description></description>
      <id>dcd7d6ce-c784-4763-b8e9-0eac1d3e7d34</id>
      <masked>false</masked>
      <name>rCardYear</name>
   </variables>
   <variables>
      <defaultValue>5670.41</defaultValue>
      <description></description>
      <id>f2edfb22-3294-49fc-9565-7489d5ed6430</id>
      <masked>false</masked>
      <name>rPriceWithExpense</name>
   </variables>
   <variables>
      <defaultValue>300</defaultValue>
      <description></description>
      <id>1aff096a-af6d-4032-a397-65570dfbf567</id>
      <masked>false</masked>
      <name>rExpense</name>
   </variables>
   <variables>
      <defaultValue>'012'</defaultValue>
      <description></description>
      <id>c33660d1-80be-4b34-8313-afe26d17fe33</id>
      <masked>false</masked>
      <name>rNumInstallments</name>
   </variables>
   <variables>
      <defaultValue>false</defaultValue>
      <description></description>
      <id>9162f013-f9c1-4da7-887d-577876e12c2c</id>
      <masked>false</masked>
      <name>rExpenseOnFirstInstallment</name>
   </variables>
   <variables>
      <defaultValue>548.14</defaultValue>
      <description></description>
      <id>03a07b5c-7599-40be-8c64-1853b5733239</id>
      <masked>false</masked>
      <name>rInstallmentAmount</name>
   </variables>
   <variables>
      <defaultValue>'CAHA'</defaultValue>
      <description></description>
      <id>09513716-e33f-40c9-8d16-b5a3e2ffe2af</id>
      <masked>false</masked>
      <name>rBranch</name>
   </variables>
   <variables>
      <defaultValue>'SEGURO_CASA_HABITACION_APF_PROPIO_ROOT'</defaultValue>
      <description></description>
      <id>2bc659b0-5ef9-439a-b836-4a71bfb1c1a8</id>
      <masked>false</masked>
      <name>rCode</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
